// This file was generated by counterfeiter
package tokenfakes

import (
	"sync"

	"github.infra.hana.ondemand.com/cloudfoundry/aker-oauth-plugin/token"
	"golang.org/x/oauth2"
)

type FakeDecoder struct {
	DecodeStub        func(token *oauth2.Token) (token.Info, error)
	decodeMutex       sync.RWMutex
	decodeArgsForCall []struct {
		token *oauth2.Token
	}
	decodeReturns struct {
		result1 token.Info
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDecoder) Decode(token *oauth2.Token) (token.Info, error) {
	fake.decodeMutex.Lock()
	fake.decodeArgsForCall = append(fake.decodeArgsForCall, struct {
		token *oauth2.Token
	}{token})
	fake.recordInvocation("Decode", []interface{}{token})
	fake.decodeMutex.Unlock()
	if fake.DecodeStub != nil {
		return fake.DecodeStub(token)
	} else {
		return fake.decodeReturns.result1, fake.decodeReturns.result2
	}
}

func (fake *FakeDecoder) DecodeCallCount() int {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	return len(fake.decodeArgsForCall)
}

func (fake *FakeDecoder) DecodeArgsForCall(i int) *oauth2.Token {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	return fake.decodeArgsForCall[i].token
}

func (fake *FakeDecoder) DecodeReturns(result1 token.Info, result2 error) {
	fake.DecodeStub = nil
	fake.decodeReturns = struct {
		result1 token.Info
		result2 error
	}{result1, result2}
}

func (fake *FakeDecoder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeDecoder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ token.Decoder = new(FakeDecoder)
